/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ['var(--font-clash)', 'Georgia', 'serif'],
        sans: ['var(--font-geist)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-plex)', 'Menlo', 'Consolas', 'monospace'],
      },
      colors: {
        'primary': '#ff9157',
        'primary-container': '#ff7a2c',
        'primary-dim': '#ff7520',
        'primary-fixed': '#ff7a2c',
        'primary-fixed-dim': '#f46800',
        'on-primary': '#531e00',
        'on-primary-container': '#401600',
        'on-primary-fixed': '#000000',
        'on-primary-fixed-variant': '#4f1d00',
        'inverse-primary': '#a04200',
        'secondary': '#e5e2e1',
        'secondary-container': '#474746',
        'secondary-dim': '#d6d4d3',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#d6d4d3',
        'on-secondary': '#525151',
        'on-secondary-container': '#d2d0cf',
        'on-secondary-fixed': '#403f3f',
        'on-secondary-fixed-variant': '#5c5b5b',
        'tertiary': '#ffc252',
        'tertiary-container': '#f7b21f',
        'tertiary-dim': '#e7a407',
        'tertiary-fixed': '#f7b21f',
        'tertiary-fixed-dim': '#e7a407',
        'on-tertiary': '#5b3e00',
        'on-tertiary-container': '#4f3600',
        'on-tertiary-fixed': '#342200',
        'on-tertiary-fixed-variant': '#5b3e00',
        'surface': '#0e0e0e',
        'surface-dim': '#0e0e0e',
        'surface-bright': '#2c2c2c',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#131313',
        'surface-container': '#191919',
        'surface-container-high': '#1f1f1f',
        'surface-container-highest': '#262626',
        'surface-variant': '#262626',
        'surface-tint': '#ff9157',
        'on-surface': '#ffffff',
        'on-surface-variant': '#ababab',
        'on-background': '#ffffff',
        'inverse-surface': '#f9f9f9',
        'inverse-on-surface': '#555555',
        'background': '#0e0e0e',
        'outline': '#757575',
        'outline-variant': '#484848',
        'error': '#ff7351',
        'error-dim': '#d53d18',
        'error-container': '#b92902',
        'on-error': '#450900',
        'on-error-container': '#ffd2c8',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out forwards',
        'slide-up': 'slideUp 0.6s ease-out forwards',
        'scroll-bounce': 'scrollBounce 1.5s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scrollBounce: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(8px)' },
        },
      },
    },
  },
  plugins: [],
}
